#  1、创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

In [1]:
import numpy as f
a=f.zeros(10,dtype=int)
print(a)
print('\n')
a[4]=1
print(a)

[0 0 0 0 0 0 0 0 0 0]


[0 0 0 0 1 0 0 0 0 0]


#  2. 创建一个5*3随机矩阵和一个3*2随机矩阵，求矩阵积

In [2]:
import numpy as f
a=f.arange(15).reshape(5,3)
b=f.arange(6).reshape(3,2)
print(a)
print('\n')
print(b)
print('\n')
print(f.dot(a,b))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


[[0 1]
 [2 3]
 [4 5]]


[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


# 3. 实现冒泡排序法

In [8]:
import numpy as f
a=[4,5,6,8,7,50,32]
b=len(a)
print(b)
for i in range(b-1):
    print(i)
    for j in range(b-1-i):
        if a[j]>a[j+1]:
            a[j],a[j+1]=a[j+1],a[j]
print(a)

7
0
1
2
3
4
5
[4, 5, 6, 7, 8, 32, 50]


# 4. 找到数组[1,2,0,0,4,0]中0元素的位置索引

In [9]:
a=[1,2,0,0,4,0]
b=[i for i,x in enumerate(a) if x==0]
print(b)

[2, 3, 5]


# 5. 创建一个 10x10 的随机数组并找到它的最大值和最小值

In [10]:
import numpy as f
a=f.random.randint(0,100,100).reshape(10,10)
print(a)
print(f.max(a))
print(f.min(a))

[[64  7 92 70 49 82 31 27 10 12]
 [92 63 45 91 61 33 78 47  7 86]
 [26 75 52 12 60 84 94 60 79 97]
 [63 39 17  7  1 39 36 78 81 36]
 [45 73 44 59 87 62 44 73 58 92]
 [71 24 76 43 17 79 83 53 28 56]
 [80 13 20  2 72 30 16 78 18  3]
 [ 9 84 32 42 40 56 48 47 82 10]
 [39  7 64  2 28 43 21  6 23 63]
 [67 35 29 51 17  1 64 69 78 21]]
97
1


# 6. 求解方程：3x1+3.2x2=118.4        3.5x1+3.6x2=135.2

In [11]:
import numpy as f
a=f.array([[3,3.2],[3.5,3.6]])
b=f.array([118.4,135.2])
s=f.linalg.solve(a,b)
print(s)

[16. 22.]
